### ISSUE TITLE
ATOMIC09 

### ISSUE THREAD

**Issue by cravlex** [ATOMIC09/DerDoS#3]
/

**Comment by cravlex** [comment]
?

**Comment by ATOMIC09** [comment]
Ok, feel free to contact me. I'm not a Hamachi expert, but I'll help where I can.

**Comment by cravlex** [comment]
I wrote to you at your email 
phutawanchanrueng@gmail.com](mailto:phutawanchanrueng@gmail.com

**Comment by cravlex** [comment]
sent you a friend request on discord

> Ok, feel free to contact me. I'm not a Hamachi expert, but I'll help where I can.
